# Configuration for Travis continuous integration
---

sudo: false
language: python
python:
    - 3.6

install:
    - pip install .
    - pip install -r requirements-dev.txt
script:
    - python -m pytest

git:
    depth: 10       # no more history to save on bandwidth

notifications:
    emails: false
